# Generated by Django 3.2.5 on 2021-07-16 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore1', '0002_auto_20210714_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='explore',
            name='body',
            field=models.TextField(max_length=10000),
        ),
    ]
